[users.takeda]
display_name = "Takeda"
role = "user"
salt = "e4dc49b867bf5854"
hash = "2e4e1741344601aac77c57bc93bf11969062dd5707ddd8fcdc9a4224ff859ff4"

[users.Naruto]
display_name = "Naruto"
role = "user"
salt = "d5efb837444ba344"
hash = "6d63f61beeca0001f611681f10be00c2d2b92e7031ecddf5a7337cb967eba317"

[gcp_service_account]
type = "service_account"
project_id = "your-project-id"
private_key_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqh...\n-----END PRIVATE KEY-----\n"
client_email = "sheet-bot@your-project-id.iam.gserviceaccount.com"
client_id = "1234567890"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/sheet-bot%40your-project-id.iam.gserviceaccount.com"
